server:
  port: 8080
  shutdown: graceful
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transferz
    username: transferz
    password: transferz
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
management:
  endpoints:
    web:
      exposure:
        include: 'info,health,metrics'
business:
  flight-limit: 150
