# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.10
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/postgresql/data
      - ../src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8082"
volumes:
  postgres_data:
    driver: local
